language: python

os: linux
dist: focal

install:
  - pip install -r requirements.txt

script:
  - make html
  - touch build/html/.nojekyll

branches:
  except:
  - gh-pages

deploy:
  provider: pages
  strategy: git
  skip_cleanup: true
  token: $GITHUB_TOKEN
  local_dir: build/html
  on:
    branch: main

notifications:
  email:
    on_success: never
    on_failure: always
